### ISSUE TITLE
Midi not declared

### ISSUE THREAD

**Issue by Birbpal** [silveirago/DIY-Midi-Controller-full#2]
Im really confused what this problem is, I'm using this code to make my first prototype midi controller. I'm struggling because of one problem as i claimed midi not declared. I have everything required and done. i'm using a Arduino mega 2560 r3. I even restarted everything just to fix it and its still there. If anyone knows anything please tell me.

**Comment by vamix2012** [comment]
You can have somewhere a missing curly bracket

**Comment by vamix2012** [comment]
Paste your code here

**Comment by Birbpal** [comment]
i got it fixed

**Comment by vamix2012** [comment]
Can you provide information about how did you fixed it

**Comment by Neurogami** [comment]
Yes, please provide details.  Someone else will inevitably have a similar issue, so might as well leave some info.
