### ISSUE TITLE
Constant changing

### ISSUE THREAD

**Issue by Will-ctrl-alt** [silveirago/DIY-Midi-Controller-full#4]
I am very new to coding and Arduinos' in general. Whenever I turn my controller on using this code I just get a bunch of random midi numbers instead of one where I can toggle on and off the buttons and use the potentiometers. I am using a pro micro with 4 potentiometers and 4 buttons. There is a picture attached on what I get with this. It just spits at me random midi numbers that I have no idea what to do with and how to fix. Help would be very much appreciated
![Screenshot 2022-05-29 110433](https://user-images.githubusercontent.com/84151245/170862645-5bf03df2-55b4-47dd-a632-470bcaa79ae9.jpg)

**Comment by m-r-m-s** [comment]
I do not use this MIDI monitor application but that looks like a Hexadecimal version of the MIDI output. Perhaps there is a way to change in the monitors preferences what output or "view" you are receiving? Here's the manual for reference:
[https://www-morson-jp.translate.goog/pocketmidi-webpage/manual/pocketmidi/pocketmidi_operation_manual_ja.html?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en-US#_%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB](https://www-morson-jp.translate.goog/pocketmidi-webpage/manual/pocketmidi/pocketmidi_operation_manual_ja.html?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en-US#_%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB)

**Comment by Will-ctrl-alt** [comment]
Firstly sorry for the delayed reply but I am not 100% sure what you mean by this or how this will resolve my issue. Because I don't get how changing what I am viewing will change the fact that nothing is on and I am getting an output which I do not believe that it should be

**Comment by Will-ctrl-alt** [comment]
Firstly sorry for the delayed reply but I am not 100% sure what you mean by this or how this will resolve my issue. Because I don't get how changing what I am viewing will change the fact that nothing is on and I am getting an output which I do not believe that it should be

**Comment by m-r-m-s** [comment]
> Firstly sorry for the delayed reply but I am not 100% sure what you mean by this or how this will resolve my issue. Because I don't get how changing what I am viewing will change the fact that nothing is on and I am getting an output which I do not believe that it should be

I suggested changing the output format (view) so you might better determine what was being output to help troubleshoot. In other words: knowing what exactly is being output may help figure out the problem. Perhaps @silveirago can chime in as well.
